const LABELS: Record<string, string> = {
  capacity_constraint: "Capacity constraint",
  supplier_delay: "Supplier delay",
  quality_escape: "Quality escape",
  pricing_pressure: "Pricing pressure",
  regulatory_change: "Regulatory change",
  contract_loss: "Contract loss",
  government_contract_award: "Government contract award",
  funding_round: "Funding round",
  contract_win: "Contract win",
  demand_spike: "Demand spike",
  hiring_surge: "Hiring surge",
  current_customer: "Current customer",
  active_pipeline: "Active pipeline",
  past_customer: "Past customer",
  target_prospect: "Target prospect",
  new_logo: "New logo",
  partner: "Partner",
  competitor: "Competitor",
  candidate_account_match: "Candidate account match",
  confirmed_account_development: "Confirmed account development",
  market_level: "Market level",
  needs_account_match: "Needs account match",
  needs_review: "Needs review",
  new_high: "New and high relevance",
  workspace_fact: "Workspace fact",
  public_fact: "Public fact",
  derived_analysis: "Derived analysis",
  market_level_hypothesis: "Market-level hypothesis",
  missing_information: "Missing information",
  work_item: "Work item",
  work_item_audit: "Work history",
  work_item_note: "Work note",
  signal_relationship: "Signal-account relationship",
  score_snapshot: "Score snapshot",
  scoring_weights: "Scoring weights",
  actionPriority: "Action priority",
  PWIN: "Probability of win",
  pwin: "Probability of win",
};

export function displayLabel(value: string | undefined): string {
  if (!value) return "";
  return LABELS[value] ?? value.replace(/_/g, " ").replace(/\b\w/g, (char) => char.toUpperCase());
}
