"""initial schema

Revision ID: 1babbd97ca12
Revises: 
Create Date: 2026-07-12 11:41:33.174804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1babbd97ca12'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_accounts',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('hubspot_company_id', sa.String(length=80), nullable=False),
    sa.Column('domains', sa.JSON(), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('facility_names', sa.JSON(), nullable=True),
    sa.Column('parent_id', sa.String(length=80), nullable=True),
    sa.Column('subsidiary_ids', sa.JSON(), nullable=True),
    sa.Column('cage_code', sa.String(length=32), nullable=True),
    sa.Column('uei', sa.String(length=32), nullable=True),
    sa.Column('known_programs', sa.JSON(), nullable=True),
    sa.Column('known_customers', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'hubspot_company_id', name='uq_canonical_hubspot_company')
    )
    op.create_index(op.f('ix_canonical_accounts_hubspot_company_id'), 'canonical_accounts', ['hubspot_company_id'], unique=False)
    op.create_index(op.f('ix_canonical_accounts_tenant_id'), 'canonical_accounts', ['tenant_id'], unique=False)
    op.create_table('connections',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('signing_secret', sa.String(length=256), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connections_tenant_id'), 'connections', ['tenant_id'], unique=False)
    op.create_table('engine_configs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', 'version', name='uq_engine_config_version')
    )
    op.create_index(op.f('ix_engine_configs_name'), 'engine_configs', ['name'], unique=False)
    op.create_index(op.f('ix_engine_configs_tenant_id'), 'engine_configs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_engine_configs_updated_at'), 'engine_configs', ['updated_at'], unique=False)
    op.create_table('hubspot_task_audits',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('hubspot_task_id', sa.String(length=80), nullable=False),
    sa.Column('record_url', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=256), nullable=True),
    sa.Column('associations', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hubspot_task_audits_created_at'), 'hubspot_task_audits', ['created_at'], unique=False)
    op.create_index(op.f('ix_hubspot_task_audits_hubspot_task_id'), 'hubspot_task_audits', ['hubspot_task_id'], unique=False)
    op.create_index(op.f('ix_hubspot_task_audits_idempotency_key'), 'hubspot_task_audits', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_hubspot_task_audits_tenant_id'), 'hubspot_task_audits', ['tenant_id'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mechanism', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('item_counts', sa.JSON(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('config_path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_status'), 'pipeline_runs', ['status'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_tenant_id'), 'pipeline_runs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_triggered_at'), 'pipeline_runs', ['triggered_at'], unique=False)
    op.create_table('work_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('canonical_account_id', sa.String(length=80), nullable=True),
    sa.Column('source_signal_ids', sa.JSON(), nullable=True),
    sa.Column('owner', sa.String(length=160), nullable=True),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('generated_artifact_ref', sa.Text(), nullable=True),
    sa.Column('approval_state', sa.String(length=32), nullable=False),
    sa.Column('execution_state', sa.String(length=32), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_system', sa.String(length=40), nullable=True),
    sa.Column('external_record_id', sa.String(length=120), nullable=True),
    sa.Column('external_record_url', sa.Text(), nullable=True),
    sa.Column('execution_idempotency_key', sa.String(length=256), nullable=True),
    sa.Column('execution_error', sa.Text(), nullable=True),
    sa.Column('audit_history', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_items_approval_state'), 'work_items', ['approval_state'], unique=False)
    op.create_index(op.f('ix_work_items_canonical_account_id'), 'work_items', ['canonical_account_id'], unique=False)
    op.create_index(op.f('ix_work_items_created_at'), 'work_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_work_items_due_date'), 'work_items', ['due_date'], unique=False)
    op.create_index(op.f('ix_work_items_execution_idempotency_key'), 'work_items', ['execution_idempotency_key'], unique=False)
    op.create_index(op.f('ix_work_items_execution_state'), 'work_items', ['execution_state'], unique=False)
    op.create_index(op.f('ix_work_items_external_record_id'), 'work_items', ['external_record_id'], unique=False)
    op.create_index(op.f('ix_work_items_external_system'), 'work_items', ['external_system'], unique=False)
    op.create_index(op.f('ix_work_items_follow_up_date'), 'work_items', ['follow_up_date'], unique=False)
    op.create_index(op.f('ix_work_items_owner'), 'work_items', ['owner'], unique=False)
    op.create_index(op.f('ix_work_items_priority'), 'work_items', ['priority'], unique=False)
    op.create_index(op.f('ix_work_items_status'), 'work_items', ['status'], unique=False)
    op.create_index(op.f('ix_work_items_tenant_id'), 'work_items', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_work_items_type'), 'work_items', ['type'], unique=False)
    op.create_index(op.f('ix_work_items_updated_at'), 'work_items', ['updated_at'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('connection_id', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=256), nullable=True),
    sa.Column('event_type', sa.String(length=120), nullable=True),
    sa.Column('raw_body', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_connection_id'), 'events', ['connection_id'], unique=False)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    op.create_table('dead_letters',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('moved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('replayed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_dead_event')
    )
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('outbound_log',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbound_log_event_id'), 'outbound_log', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbound_log_event_id'), table_name='outbound_log')
    op.drop_table('outbound_log')
    op.drop_table('idempotency_keys')
    op.drop_table('dead_letters')
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_index(op.f('ix_events_connection_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_work_items_updated_at'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_type'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_tenant_id'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_status'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_priority'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_owner'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_follow_up_date'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_external_system'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_external_record_id'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_execution_state'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_execution_idempotency_key'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_due_date'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_created_at'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_canonical_account_id'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_approval_state'), table_name='work_items')
    op.drop_table('work_items')
    op.drop_index(op.f('ix_pipeline_runs_triggered_at'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_tenant_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_status'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_hubspot_task_audits_tenant_id'), table_name='hubspot_task_audits')
    op.drop_index(op.f('ix_hubspot_task_audits_idempotency_key'), table_name='hubspot_task_audits')
    op.drop_index(op.f('ix_hubspot_task_audits_hubspot_task_id'), table_name='hubspot_task_audits')
    op.drop_index(op.f('ix_hubspot_task_audits_created_at'), table_name='hubspot_task_audits')
    op.drop_table('hubspot_task_audits')
    op.drop_index(op.f('ix_engine_configs_updated_at'), table_name='engine_configs')
    op.drop_index(op.f('ix_engine_configs_tenant_id'), table_name='engine_configs')
    op.drop_index(op.f('ix_engine_configs_name'), table_name='engine_configs')
    op.drop_table('engine_configs')
    op.drop_index(op.f('ix_connections_tenant_id'), table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_canonical_accounts_tenant_id'), table_name='canonical_accounts')
    op.drop_index(op.f('ix_canonical_accounts_hubspot_company_id'), table_name='canonical_accounts')
    op.drop_table('canonical_accounts')
    # ### end Alembic commands ###
