"""add connection destination url

Revision ID: 8233aeb6057e
Revises: 1babbd97ca12
Create Date: 2026-07-12 11:45:13.466936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8233aeb6057e'
down_revision: Union[str, Sequence[str], None] = '1babbd97ca12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('destination_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connections', 'destination_url')
    # ### end Alembic commands ###
