from __future__ import annotations

from datetime import UTC, datetime, timedelta
from typing import Any

DEMO_TENANT_ID = "btx-demo-command-cockpit"
DEMO_DISPLAY_NAME = "BTX Demonstration Workspace"
DEMO_ACTOR = "demo.reset@btx.local"


def _iso(dt: datetime) -> str:
    return dt.astimezone(UTC).isoformat().replace("+00:00", "Z")


def _at(anchor: datetime, *, days: int = 0, hours: int = 0) -> datetime:
    return anchor.astimezone(UTC).replace(minute=0, second=0, microsecond=0) + timedelta(days=days, hours=hours)


def _signal(
    *,
    signal_id: str,
    title: str,
    source: str,
    url: str,
    event_type: str,
    entities: list[str],
    quote: str,
    detected_at: datetime,
    scope: str = "market",
    subject_id: str = "__portfolio__",
    relevance: int = 75,
    value: int | None = None,
) -> dict[str, Any]:
    return {
        "id": signal_id,
        "event_type": event_type,
        "entities": entities,
        "subject_id": subject_id,
        "scope": scope,
        "value": value,
        "confidence": relevance / 100,
        "source_quote": quote,
        "source_url": url,
        "document_url": url,
        "detected_at": _iso(detected_at),
        "dataClassification": "public",
        "artifact": {
            "item_id": signal_id.removeprefix("demo-sig-"),
            "headline": title,
            "source_name": source,
            "source_date": _iso(detected_at),
            "run_at": _iso(detected_at),
            "signal_type": event_type,
            "relevance_score": relevance,
            "analysis_text": quote,
            "source_url": url,
            "dollar_figures": [value] if value else [],
            "affected_entities": entities,
            "provenance": {
                "classification": "public",
                "source": source,
                "url": url,
                "note": "Seeded from repository monitor artifact metadata; no live web research performed during reset.",
            },
        },
    }


def build_demo_seed(anchor: datetime | None = None) -> dict[str, Any]:
    reset_at = (anchor or datetime.now(UTC)).astimezone(UTC).replace(microsecond=0)
    detected_three_days_ago = _at(reset_at, days=-3)
    detected_two_days_ago = _at(reset_at, days=-2)
    detected_yesterday = _at(reset_at, days=-1)
    due_today = _at(reset_at, hours=4)
    due_tomorrow = _at(reset_at, days=1)
    due_next_week = _at(reset_at, days=7)

    accounts = [
        {
            "id": "demo-acct-lockheed",
            "name": "Lockheed Martin Corporation",
            "relationship": "customer",
            "domains": ["lockheedmartin.com"],
            "aliases": ["Lockheed Martin", "Lockheed", "Lockheed Martin Aeronautics"],
            "known_programs": ["F-35 Lightning II", "Directed-energy laser defense", "Hypersonics"],
            "known_customers": ["Department of Defense", "U.S. Air Force"],
            "cage_code": "06887",
            "uei": "CQWLW9XRQTH5",
            "city": "Fort Worth",
            "state": "TX",
            "needs": ["5-axis CNC", "AS9100", "ITAR", "build-to-print", "thermal-management hardware"],
        },
        {
            "id": "demo-acct-rtx",
            "name": "RTX Corporation",
            "relationship": "customer",
            "domains": ["rtx.com"],
            "aliases": ["RTX", "Raytheon", "Raytheon Technologies"],
            "known_programs": ["Patriot Air Defense", "Hypersonics", "F135 engine"],
            "known_customers": ["Department of Defense"],
            "cage_code": "96214",
            "city": "Arlington",
            "state": "VA",
            "needs": ["precision machining", "missile components", "ITAR"],
        },
        {
            "id": "demo-acct-northrop",
            "name": "Northrop Grumman Corporation",
            "relationship": "customer",
            "domains": ["northropgrumman.com"],
            "aliases": ["Northrop Grumman", "Northrop", "NGC"],
            "known_programs": ["B-21 Raider", "Sentinel", "Hypersonics"],
            "known_customers": ["Department of Defense"],
            "cage_code": "76823",
            "city": "Falls Church",
            "state": "VA",
            "needs": ["build-to-print", "space-qualified machining", "AS9100"],
        },
        {
            "id": "demo-acct-nlight",
            "name": "nLIGHT, Inc.",
            "relationship": "target",
            "domains": ["nlight.net"],
            "aliases": ["nLIGHT", "nLight"],
            "known_programs": ["Directed-energy laser defense"],
            "known_customers": ["Department of Defense"],
            "city": "Camas",
            "state": "WA",
            "needs": ["optical benches", "thermal-management housings", "precision alignment components"],
        },
        {
            "id": "demo-acct-pulse-space",
            "name": "Pulse Space Technologies",
            "relationship": "target",
            "domains": ["pulsespace.com"],
            "aliases": ["Pulse Space", "Pulse Space Technologies"],
            "known_programs": ["Laser power transmission"],
            "known_customers": ["U.S. Space Force"],
            "city": "Los Angeles",
            "state": "CA",
            "needs": ["space-rated structures", "thermal-management hardware", "prototype machining"],
        },
        {
            "id": "demo-acct-collins",
            "name": "Collins Aerospace",
            "relationship": "customer",
            "domains": ["collinsaerospace.com"],
            "aliases": ["Collins", "Collins Aerospace"],
            "known_programs": ["Avionics", "Landing systems", "Actuation systems"],
            "known_customers": ["RTX Corporation"],
            "city": "Charlotte",
            "state": "NC",
            "needs": ["actuation hardware", "precision components"],
        },
    ]

    signals = [
        _signal(
            signal_id="demo-sig-lockheed-laser",
            title="Pentagon picks Lockheed, nLIGHT for laser defense project",
            source="Breaking Defense",
            url="https://breakingdefense.com/2026/07/pentagon-picks-lockheed-nlight-for-laser-defense-project/",
            event_type="government_contract_award",
            entities=["Lockheed Martin Corporation", "nLIGHT, Inc.", "Department of Defense"],
            subject_id="demo-acct-lockheed",
            scope="specific_account",
            relevance=86,
            detected_at=detected_three_days_ago,
            quote="Lockheed Martin and nLIGHT were selected for a Pentagon laser-defense project; the repository artifact flags potential precision housings, mounts, optical benches, and thermal-management hardware.",
        ),
        _signal(
            signal_id="demo-sig-nlight-laser",
            title="nLIGHT named in Pentagon directed-energy selection",
            source="Breaking Defense",
            url="https://breakingdefense.com/2026/07/pentagon-picks-lockheed-nlight-for-laser-defense-project/",
            event_type="government_contract_award",
            entities=["nLIGHT, Inc.", "Lockheed Martin Corporation"],
            relevance=72,
            detected_at=detected_three_days_ago,
            quote="nLIGHT appears in the same sourced directed-energy item. The account link remains unresolved until a user confirms whether BTX should pursue nLIGHT directly or through Lockheed.",
        ),
        _signal(
            signal_id="demo-sig-hypersonics-gao",
            title="GAO: Pentagon hypersonic programs face schedule and production constraints",
            source="DefenseScoop",
            url="https://defensescoop.com/2026/07/07/gao-pentagon-hypersonic-programs-schedule-constraints-production-woes/",
            event_type="capacity_constraint",
            entities=["hypersonic weapons", "Department of Defense", "Lockheed Martin Corporation", "RTX Corporation"],
            scope="program",
            relevance=82,
            detected_at=detected_two_days_ago,
            quote="GAO flagged schedule constraints and production challenges in Pentagon hypersonic programs, creating a capacity-review opening for certified build-to-print suppliers.",
        ),
        _signal(
            signal_id="demo-sig-pulse-space",
            title="Space Force awards Pulse Space $40 million to advance laser power technology",
            source="SpaceNews",
            url="https://spacenews.com/space-force-awards-pulse-space-40-million-to-advance-laser-power-technology/",
            event_type="government_contract_award",
            entities=["Pulse Space Technologies", "U.S. Space Force"],
            relevance=76,
            value=40_000_000,
            detected_at=detected_yesterday,
            quote="Space Force awarded $40 million to Pulse Space for laser power-transmission technology; subcontract relevance is not confirmed and should remain a research target.",
        ),
        _signal(
            signal_id="demo-sig-pqc-compliance",
            title="Pentagon post-quantum cryptography directive may affect defense contractors",
            source="DefenseScoop",
            url="https://defensescoop.com/2026/07/10/cmmc-pqc-requirements-defense-contractors-cybersecurity/",
            event_type="regulatory_change",
            entities=["Department of Defense"],
            scope="market",
            relevance=64,
            detected_at=detected_yesterday,
            quote="DoD is moving toward post-quantum cryptography requirements in CMMC, a market-level compliance watch item for defense subcontractors.",
        ),
        _signal(
            signal_id="demo-sig-space-force-portfolios",
            title="Space Force acquisition reorganization creates portfolio-level decision makers",
            source="Repository archive",
            url="https://www.spaceforce.mil/",
            event_type="market_structure_change",
            entities=["U.S. Space Force", "Lockheed Martin Corporation", "Northrop Grumman Corporation"],
            scope="market",
            relevance=66,
            detected_at=detected_two_days_ago,
            quote="The repository archive summarizes a Space Force acquisition reorganization that may change how prime contractors navigate subcontracting pathways.",
        ),
        _signal(
            signal_id="demo-sig-directed-energy-market",
            title="Directed-energy demand creates precision-machining watch item",
            source="Repository archive",
            url="https://defensescoop.com/2026/07/09/pentagon-joint-laser-weapon-system-defeat-drone-swarms/",
            event_type="demand_spike",
            entities=["Lockheed Martin Corporation", "RTX Corporation", "Northrop Grumman Corporation"],
            scope="market",
            relevance=70,
            detected_at=detected_yesterday,
            quote="Repository artifacts connect directed-energy awards to possible optical, thermal, and structural hardware demand, but no specific BTX subcontract is confirmed.",
        ),
    ]

    relationships = [
        {
            "id": "demo-rel-lockheed-laser",
            "signal_id": "demo-sig-lockheed-laser",
            "canonical_account_id": "demo-acct-lockheed",
            "source_entity_name": "Lockheed Martin Corporation",
            "match_method": "exact_legal_name",
            "confidence": 0.96,
            "review_status": "confirmed",
            "creation_source": "public_data",
            "evidence_ids": ["demo-sig-lockheed-laser"],
            "confirmed_by_user_id": "jamie.demo@btx.local",
            "confirmed_at": _at(reset_at, days=-2),
        },
        {
            "id": "demo-rel-nlight-review",
            "signal_id": "demo-sig-nlight-laser",
            "canonical_account_id": "demo-acct-nlight",
            "source_entity_name": "nLIGHT, Inc.",
            "match_method": "verified_alias",
            "confidence": 0.72,
            "review_status": "needs_review",
            "creation_source": "derived",
            "evidence_ids": ["demo-sig-nlight-laser"],
            "confirmed_by_user_id": None,
            "confirmed_at": None,
        },
    ]

    work_items = [
        {
            "id": "demo-wi-approve-lockheed",
            "type": "hubspot_task",
            "canonical_account_id": "demo-acct-lockheed",
            "related_signal_id": "demo-sig-lockheed-laser",
            "related_relationship_id": "demo-rel-lockheed-laser",
            "program_id": "directed-energy",
            "source_signal_ids": ["demo-sig-lockheed-laser"],
            "supporting_evidence": [{"id": "demo-sig-lockheed-laser", "dataClassification": "public"}],
            "missing_information": ["Subcontracting ownership between Lockheed and nLIGHT"],
            "dedupe_key": "demo:approval:lockheed-laser",
            "owner": "Jamie Goettler",
            "priority": "urgent",
            "status": "awaiting_approval",
            "due_date": due_today,
            "description": "Review the sourced directed-energy development and approve a CRM task for the Lockheed relationship owner.",
            "recommended_action": "Approve Lockheed directed-energy follow-up task",
            "generated_artifact_ref": "demo-deliv-lockheed-brief",
            "approval_state": "pending",
            "execution_state": "not_started",
            "follow_up_date": due_next_week,
        },
        {
            "id": "demo-wi-review-nlight",
            "type": "relationship_review",
            "canonical_account_id": "demo-acct-nlight",
            "related_signal_id": "demo-sig-nlight-laser",
            "related_relationship_id": "demo-rel-nlight-review",
            "program_id": "directed-energy",
            "source_signal_ids": ["demo-sig-nlight-laser"],
            "supporting_evidence": [{"id": "demo-sig-nlight-laser", "dataClassification": "public"}],
            "missing_information": ["Whether nLIGHT should be handled as direct prospect or partner-through-prime"],
            "dedupe_key": "relationship_review:btx-demo-command-cockpit:demo-rel-nlight-review",
            "owner": "Revenue Ops",
            "priority": "high",
            "status": "triaged",
            "due_date": due_tomorrow,
            "description": "Confirm the signal-account match before treating this as a direct account fact.",
            "recommended_action": "Review nLIGHT relationship to directed-energy signal",
            "approval_state": "not_required",
            "execution_state": "not_started",
            "follow_up_date": due_next_week,
        },
        {
            "id": "demo-wi-capacity-hyp",
            "type": "capacity_check",
            "canonical_account_id": "demo-acct-rtx",
            "related_signal_id": "demo-sig-hypersonics-gao",
            "program_id": "hypersonics",
            "source_signal_ids": ["demo-sig-hypersonics-gao"],
            "supporting_evidence": [{"id": "demo-sig-hypersonics-gao", "dataClassification": "public"}],
            "missing_information": ["ERP/MES capacity feed is not connected"],
            "dedupe_key": "demo:capacity:hypersonics",
            "owner": "Operations",
            "priority": "high",
            "status": "prepared",
            "due_date": due_tomorrow,
            "description": "Assess whether BTX could support surge build-to-print demand if primes need schedule-risk mitigation.",
            "recommended_action": "Run capacity review for hypersonics machining demand",
            "approval_state": "not_required",
            "execution_state": "not_started",
            "follow_up_date": due_next_week,
        },
        {
            "id": "demo-wi-approved-pulse",
            "type": "hubspot_task",
            "canonical_account_id": "demo-acct-pulse-space",
            "related_signal_id": "demo-sig-pulse-space",
            "program_id": "laser-power",
            "source_signal_ids": ["demo-sig-pulse-space"],
            "supporting_evidence": [{"id": "demo-sig-pulse-space", "dataClassification": "public"}],
            "missing_information": ["No verified prime integration partner"],
            "dedupe_key": "demo:approved:pulse-space",
            "owner": "BD Research",
            "priority": "normal",
            "status": "approved",
            "due_date": due_next_week,
            "description": "Prepared CRM research task. Execution remains disabled unless a sandbox HubSpot integration is configured.",
            "recommended_action": "Create Pulse Space supply-chain research task",
            "generated_artifact_ref": "demo-deliv-lockheed-brief",
            "approval_state": "approved",
            "execution_state": "not_started",
            "follow_up_date": due_next_week,
        },
        {
            "id": "demo-wi-verified-sim",
            "type": "hubspot_task",
            "canonical_account_id": "demo-acct-lockheed",
            "related_signal_id": "demo-sig-lockheed-laser",
            "program_id": "directed-energy",
            "source_signal_ids": ["demo-sig-lockheed-laser"],
            "supporting_evidence": [{"id": "demo-sig-lockheed-laser", "dataClassification": "public"}],
            "missing_information": [],
            "dedupe_key": "demo:verified:lockheed-qbr",
            "owner": "Jamie Goettler",
            "priority": "normal",
            "status": "verified",
            "due_date": _at(reset_at, days=-1),
            "description": "Illustrative local record showing a completed demonstration action. No real HubSpot mutation was issued by reset.",
            "recommended_action": "Confirm Lockheed QBR agenda included directed-energy question",
            "approval_state": "approved",
            "execution_state": "verified",
            "outcome": None,
            "external_system": "hubspot-demo",
            "external_record_id": "simulated-hubspot-task-lockheed-qbr",
            "external_record_url": None,
            "execution_idempotency_key": "demo:simulated:lockheed-qbr",
            "follow_up_date": due_tomorrow,
        },
        {
            "id": "demo-wi-closed-outcome",
            "type": "research_task",
            "canonical_account_id": "demo-acct-northrop",
            "related_signal_id": "demo-sig-directed-energy-market",
            "program_id": "directed-energy",
            "source_signal_ids": ["demo-sig-directed-energy-market"],
            "supporting_evidence": [{"id": "demo-sig-directed-energy-market", "dataClassification": "public"}],
            "missing_information": [],
            "dedupe_key": "demo:closed:northrop-market",
            "owner": "Revenue Ops",
            "priority": "low",
            "status": "closed",
            "due_date": _at(reset_at, days=-2),
            "description": "Completed illustrative research item with an outcome for demo history.",
            "recommended_action": "Log Northrop directed-energy watch item",
            "approval_state": "not_required",
            "execution_state": "not_started",
            "outcome": "Logged as watch item for next quarterly account planning review.",
            "outcome_category": "learning",
            "follow_up_date": due_next_week,
        },
    ]

    return {
        "tenant": {
            "id": DEMO_TENANT_ID,
            "display_name": DEMO_DISPLAY_NAME,
            "is_demonstration": True,
            "reference_date": reset_at,
            "metadata": {
                "programs": [
                    {"id": "directed-energy", "name": "Directed-energy laser defense", "dataClassification": "public"},
                    {"id": "hypersonics", "name": "Hypersonics production risk", "dataClassification": "public"},
                    {"id": "laser-power", "name": "Laser power transmission", "dataClassification": "public"},
                ],
                "contacts": [
                    {"id": "demo-contact-lockheed-1", "company_id": "demo-acct-lockheed", "name": "Alyssa Hart", "title": "Simulated Lockheed relationship owner", "dataClassification": "simulated"},
                    {"id": "demo-contact-rtx-1", "company_id": "demo-acct-rtx", "name": "Contact not provided", "title": "More information needed", "dataClassification": "simulated"},
                ],
                "opportunities": [
                    {"id": "demo-opp-lockheed-laser", "company_id": "demo-acct-lockheed", "name": "Directed-energy machining discovery", "value": 750000, "stage": "qualified", "close_date": due_next_week.date().isoformat(), "dataClassification": "simulated"},
                    {"id": "demo-opp-rtx-capacity", "company_id": "demo-acct-rtx", "name": "Hypersonics capacity assessment", "value": None, "stage": "prospecting", "close_date": due_next_week.date().isoformat(), "dataClassification": "simulated"},
                ],
                "facilities": [
                    {"id": "demo-facility-austin-cell", "company_id": "demo-acct-lockheed", "city": "Austin", "state": "TX", "address": "Illustrative BTX partner cell", "lat": 30.2672, "lon": -97.7431, "kind": "plant", "dataClassification": "simulated"}
                ],
                "sourceHealth": [
                    {"sourceKey": "hubspot-demo", "displayName": "Illustrative CRM seed", "availability": "simulated", "recordCount": 8, "errorCode": None, "errorMessage": "CRM records are illustrative for this demonstration workspace."},
                    {"sourceKey": "monitor", "displayName": "Monitor pipeline", "availability": "stale", "recordCount": 7, "lastSuccessfulSyncAt": _iso(detected_yesterday), "errorCode": None, "errorMessage": None},
                    {"sourceKey": "operating", "displayName": "ERP / MES operating data", "availability": "not_configured", "recordCount": 0, "errorCode": "not_configured", "errorMessage": "Operating data is not connected; capacity findings are illustrative manual checks."},
                ],
                "notice": "Public intelligence is sourced. Internal BTX records are illustrative.",
            },
        },
        "accounts": accounts,
        "signals": signals,
        "relationships": relationships,
        "work_items": work_items,
        "notes": [
            {"id": "demo-note-approve-1", "work_item_id": "demo-wi-approve-lockheed", "author_user_id": "jamie.demo@btx.local", "body": "Simulated internal note: confirm whether the Lockheed laser team owns machining strategy before outreach.", "note_type": "finding", "evidence_ids": ["demo-sig-lockheed-laser"], "created_at": _at(reset_at, days=-1)},
            {"id": "demo-note-verified-1", "work_item_id": "demo-wi-verified-sim", "author_user_id": "system", "body": "Simulated verification: local demo record only. Reset did not create or verify a real HubSpot task.", "note_type": "verification", "evidence_ids": ["demo-sig-lockheed-laser"], "created_at": _at(reset_at, days=-1, hours=1)},
            {"id": "demo-note-closed-1", "work_item_id": "demo-wi-closed-outcome", "author_user_id": "revenue.ops@btx.local", "body": "Outcome recorded: keep Northrop in market watch and do not create an outreach task yet.", "note_type": "outcome", "evidence_ids": ["demo-sig-directed-energy-market"], "created_at": _at(reset_at, days=-1)},
        ],
        "deliverables": [
            {
                "id": "demo-deliv-lockheed-brief",
                "type": "meeting_brief",
                "title": "Lockheed directed-energy account brief",
                "canonical_account_id": "demo-acct-lockheed",
                "program_id": "directed-energy",
                "entity_ids": ["demo-acct-lockheed", "demo-sig-lockheed-laser"],
                "document": {
                    "id": "demo-deliv-lockheed-brief",
                    "type": "meeting_brief",
                    "title": "Lockheed directed-energy account brief",
                    "createdAt": _iso(reset_at),
                    "brainArea": "accounts",
                    "entityIds": ["demo-acct-lockheed", "demo-sig-lockheed-laser"],
                    "dataClassification": "simulated",
                    "sections": [
                        {"id": "purpose", "heading": "Purpose", "blocks": [{"kind": "text", "text": "Prepare for a practical Lockheed conversation about the sourced directed-energy development."}]},
                        {"id": "summary", "heading": "Executive summary", "blocks": [{"kind": "text", "text": "Public evidence supports a timely account review. Internal CRM context and opportunity values in this demo are illustrative."}]},
                        {"id": "sources", "heading": "Sources", "blocks": [{"kind": "text", "text": "Breaking Defense sourced item plus simulated BTX CRM/workflow records."}]},
                    ],
                    "sources": [{"source": "Breaking Defense", "records": ["demo-sig-lockheed-laser"], "reason": "Public directed-energy program development."}],
                    "confidence": "high",
                    "actions": [],
                },
            }
        ],
    }
