from __future__ import annotations

from datetime import UTC, datetime, timedelta
from typing import Any

DEMO_TENANT_ID = "btx-demo-command-cockpit"
DEMO_DISPLAY_NAME = "BTX Demonstration Workspace"
DEMO_ACTOR = "demo.reset@btx.local"
DEMO_REPOSITORY_REVISION = "779198f"


def _iso(dt: datetime) -> str:
    return dt.astimezone(UTC).isoformat().replace("+00:00", "Z")


def _at(anchor: datetime, *, days: int = 0, hours: int = 0) -> datetime:
    return anchor.astimezone(UTC).replace(minute=0, second=0, microsecond=0) + timedelta(days=days, hours=hours)


def _signal(
    *,
    signal_id: str,
    title: str,
    source: str,
    url: str,
    event_type: str,
    entities: list[str],
    quote: str,
    detected_at: datetime,
    scope: str = "market",
    subject_id: str = "__portfolio__",
    relevance: int = 75,
    value: int | None = None,
) -> dict[str, Any]:
    return {
        "id": signal_id,
        "event_type": event_type,
        "entities": entities,
        "subject_id": subject_id,
        "scope": scope,
        "value": value,
        "confidence": relevance / 100,
        "source_quote": quote,
        "source_url": url,
        "document_url": url,
        "detected_at": _iso(detected_at),
        "dataClassification": "public",
        "artifact": {
            "item_id": signal_id.removeprefix("demo-sig-"),
            "headline": title,
            "source_name": source,
            "source_date": _iso(detected_at),
            "run_at": _iso(detected_at),
            "signal_type": event_type,
            "relevance_score": relevance,
            "analysis_text": quote,
            "source_url": url,
            "dollar_figures": [value] if value else [],
            "affected_entities": entities,
            "provenance": {
                "classification": "public",
                "source": source,
                "url": url,
                "note": "Seeded from repository monitor artifact metadata; no live web research performed during reset.",
            },
        },
    }


def build_demo_seed(anchor: datetime | None = None) -> dict[str, Any]:
    reset_at = (anchor or datetime.now(UTC)).astimezone(UTC).replace(microsecond=0)
    detected_three_days_ago = _at(reset_at, days=-3)
    detected_two_days_ago = _at(reset_at, days=-2)
    detected_yesterday = _at(reset_at, days=-1)
    due_today = _at(reset_at, hours=4)
    due_tomorrow = _at(reset_at, days=1)
    due_next_week = _at(reset_at, days=7)

    accounts = [
        {
            "id": "demo-acct-lockheed",
            "name": "Lockheed Martin Corporation",
            # Real HubSpot company in the demo portal. The company record is real;
            # the BTX relationship, contact, and deal on it are illustrative.
            "hubspot_company_id": "336059557613",
            "relationship": "customer",
            "domains": ["lockheedmartin.com"],
            "aliases": ["Lockheed Martin", "Lockheed", "Lockheed Martin Aeronautics"],
            "known_programs": ["F-35 Lightning II", "Directed-energy laser defense", "Hypersonics"],
            "known_customers": ["Department of Defense", "U.S. Air Force"],
            "cage_code": "06887",
            "uei": "CQWLW9XRQTH5",
            "city": "Fort Worth",
            "state": "TX",
            "lat": 32.7555,
            "lon": -97.3308,
            "needs": ["5-axis CNC", "AS9100", "ITAR", "build-to-print", "thermal-management hardware"],
        },
        {
            "id": "demo-acct-nlight",
            "name": "nLIGHT, Inc.",
            "hubspot_company_id": "336368378559",
            "relationship": "prospect",
            "domains": ["nlight.net"],
            "aliases": ["nLIGHT", "nLight"],
            "known_programs": ["Directed-energy laser defense"],
            "known_customers": ["Department of Defense"],
            "city": "Camas",
            "state": "WA",
            "lat": 45.5871,
            "lon": -122.3995,
            "needs": ["optical benches", "thermal-management housings", "precision alignment components"],
        },
        {
            "id": "demo-acct-pulse-space",
            "name": "Pulse Space Technologies",
            "hubspot_company_id": "336368378560",
            "relationship": "prospect",
            "domains": ["pulsespace.com"],
            "aliases": ["Pulse Space", "Pulse Space Technologies"],
            "known_programs": ["Laser power transmission"],
            "known_customers": ["U.S. Space Force"],
            "city": "Bellevue",
            "state": "WA",
            "lat": 47.6101,
            "lon": -122.2015,
            "needs": ["space-rated structures", "thermal-management hardware", "prototype machining"],
        },
    ]

    signals = [
        _signal(
            signal_id="demo-sig-lockheed-laser",
            title="Pentagon picks Lockheed, nLIGHT for laser defense project",
            source="Breaking Defense",
            url="https://breakingdefense.com/2026/07/pentagon-picks-lockheed-nlight-for-laser-defense-project/",
            event_type="government_contract_award",
            entities=["Lockheed Martin Corporation", "nLIGHT, Inc.", "Department of Defense"],
            subject_id="demo-acct-lockheed",
            scope="specific_account",
            relevance=86,
            value=627_000_000,
            detected_at=detected_three_days_ago,
            quote="Lockheed Martin and nLIGHT were selected for a Pentagon laser-defense project valued at $627 million; the repository artifact flags potential precision housings, mounts, optical benches, and thermal-management hardware. The award value is the public program figure, not a BTX work-package value.",
        ),
        _signal(
            signal_id="demo-sig-nlight-laser",
            title="nLIGHT named in Pentagon directed-energy selection",
            source="Breaking Defense",
            url="https://breakingdefense.com/2026/07/pentagon-picks-lockheed-nlight-for-laser-defense-project/",
            event_type="government_contract_award",
            entities=["nLIGHT, Inc.", "Lockheed Martin Corporation"],
            relevance=72,
            detected_at=detected_three_days_ago,
            quote="nLIGHT appears in the same sourced directed-energy item. The account link remains unresolved until a user confirms whether BTX should pursue nLIGHT directly or through Lockheed.",
        ),
        _signal(
            signal_id="demo-sig-pulse-space",
            title="Space Force awards Pulse Space $40 million to advance laser power technology",
            source="SpaceNews",
            url="https://spacenews.com/space-force-awards-pulse-space-40-million-to-advance-laser-power-technology/",
            event_type="government_contract_award",
            entities=["Pulse Space Technologies", "U.S. Space Force"],
            relevance=76,
            value=40_000_000,
            detected_at=detected_yesterday,
            quote="Space Force awarded $40 million to Pulse Space for laser power-transmission technology; subcontract relevance is not confirmed and should remain a research target.",
        ),
    ]

    relationships = [
        {
            "id": "demo-rel-lockheed-laser",
            "signal_id": "demo-sig-lockheed-laser",
            "canonical_account_id": "demo-acct-lockheed",
            "source_entity_name": "Lockheed Martin Corporation",
            "match_method": "exact_legal_name",
            "confidence": 0.96,
            "review_status": "confirmed",
            "creation_source": "public_data",
            "evidence_ids": ["demo-sig-lockheed-laser"],
            "confirmed_by_user_id": "jamie.demo@btx.local",
            "confirmed_at": _at(reset_at, days=-2),
        },
        {
            "id": "demo-rel-nlight-review",
            "signal_id": "demo-sig-nlight-laser",
            "canonical_account_id": "demo-acct-nlight",
            "source_entity_name": "nLIGHT, Inc.",
            "match_method": "verified_alias",
            "confidence": 0.72,
            "review_status": "needs_review",
            "creation_source": "derived",
            "evidence_ids": ["demo-sig-nlight-laser"],
            "confirmed_by_user_id": None,
            "confirmed_at": None,
        },
    ]

    work_items = [
        {
            "id": "demo-wi-approve-lockheed",
            "type": "hubspot_task",
            "canonical_account_id": "demo-acct-lockheed",
            "related_signal_id": "demo-sig-lockheed-laser",
            "related_relationship_id": "demo-rel-lockheed-laser",
            "program_id": "directed-energy",
            "source_signal_ids": ["demo-sig-lockheed-laser"],
            "supporting_evidence": [{"id": "demo-sig-lockheed-laser", "dataClassification": "public"}],
            "missing_information": ["Subcontracting ownership between Lockheed and nLIGHT"],
            "dedupe_key": "demo:approval:lockheed-laser",
            "owner": "Jamie Goettler",
            "priority": "urgent",
            "status": "awaiting_approval",
            "due_date": due_today,
            "description": "Review the sourced directed-energy development and approve a CRM task for the Lockheed relationship owner.",
            "recommended_action": "Approve Lockheed directed-energy follow-up task",
            "generated_artifact_ref": "demo-deliv-lockheed-brief",
            "approval_state": "pending",
            "execution_state": "not_started",
            "follow_up_date": due_next_week,
        },
        {
            "id": "demo-wi-review-nlight",
            "type": "relationship_review",
            "canonical_account_id": "demo-acct-nlight",
            "related_signal_id": "demo-sig-nlight-laser",
            "related_relationship_id": "demo-rel-nlight-review",
            "program_id": "directed-energy",
            "source_signal_ids": ["demo-sig-nlight-laser"],
            "supporting_evidence": [{"id": "demo-sig-nlight-laser", "dataClassification": "public"}],
            "missing_information": ["Whether nLIGHT should be handled as direct prospect or partner-through-prime"],
            "dedupe_key": "relationship_review:btx-demo-command-cockpit:demo-rel-nlight-review",
            "owner": "Revenue Ops",
            "priority": "high",
            "status": "triaged",
            "due_date": due_tomorrow,
            "description": "Confirm the signal-account match before treating this as a direct account fact.",
            "recommended_action": "Review nLIGHT relationship to directed-energy signal",
            "approval_state": "not_required",
            "execution_state": "not_started",
            "follow_up_date": due_next_week,
        },
        {
            "id": "demo-wi-research-nlight",
            "type": "research_task",
            "canonical_account_id": "demo-acct-nlight",
            "related_signal_id": "demo-sig-nlight-laser",
            "program_id": "directed-energy",
            "source_signal_ids": ["demo-sig-nlight-laser"],
            "supporting_evidence": [{"id": "demo-sig-nlight-laser", "dataClassification": "public"}],
            "missing_information": [
                "No CAGE code on record for nLIGHT",
                "No named contact or decision owner identified",
                "Supplier fit is unconfirmed; no BTX capability match has been validated",
                "No BTX capacity commitment has been assessed for this work",
            ],
            "dedupe_key": "demo:research:nlight-qualification",
            "owner": "BD Research",
            "priority": "high",
            "status": "prepared",
            "due_date": due_tomorrow,
            "description": "Qualify nLIGHT as a directed-energy prospect before any outreach. The public award is sourced; everything BTX needs in order to act on it is still missing.",
            "recommended_action": "Qualify nLIGHT before outreach",
            "approval_state": "not_required",
            "execution_state": "not_started",
            "follow_up_date": due_next_week,
        },
        {
            "id": "demo-wi-approved-pulse",
            "type": "hubspot_task",
            "canonical_account_id": "demo-acct-pulse-space",
            "related_signal_id": "demo-sig-pulse-space",
            "program_id": "laser-power",
            "source_signal_ids": ["demo-sig-pulse-space"],
            "supporting_evidence": [{"id": "demo-sig-pulse-space", "dataClassification": "public"}],
            "missing_information": ["No verified prime integration partner"],
            "dedupe_key": "demo:approved:pulse-space",
            "owner": "BD Research",
            "priority": "normal",
            "status": "approved",
            "due_date": due_next_week,
            "description": "Prepared CRM research task. Execution remains disabled unless a sandbox HubSpot integration is configured.",
            "recommended_action": "Create Pulse Space supply-chain research task",
            "generated_artifact_ref": "demo-deliv-lockheed-brief",
            "approval_state": "approved",
            "execution_state": "not_started",
            "follow_up_date": due_next_week,
        },
        {
            "id": "demo-wi-verified-sim",
            "type": "hubspot_task",
            "canonical_account_id": "demo-acct-lockheed",
            "related_signal_id": "demo-sig-lockheed-laser",
            "program_id": "directed-energy",
            "source_signal_ids": ["demo-sig-lockheed-laser"],
            "supporting_evidence": [{"id": "demo-sig-lockheed-laser", "dataClassification": "public"}],
            "missing_information": [],
            "dedupe_key": "demo:verified:lockheed-qbr",
            "owner": "Jamie Goettler",
            "priority": "normal",
            "status": "verified",
            "due_date": _at(reset_at, days=-1),
            "description": "Illustrative local record showing a completed demonstration action. No real HubSpot mutation was issued by reset.",
            "recommended_action": "Confirm Lockheed QBR agenda included directed-energy question",
            "approval_state": "approved",
            "execution_state": "verified",
            "outcome": None,
            "external_system": "hubspot-demo",
            "external_record_id": "simulated-hubspot-task-lockheed-qbr",
            "external_record_url": None,
            "execution_idempotency_key": "demo:simulated:lockheed-qbr",
            "follow_up_date": due_tomorrow,
        },
        {
            "id": "demo-wi-closed-outcome",
            "type": "research_task",
            "canonical_account_id": "demo-acct-lockheed",
            "related_signal_id": "demo-sig-lockheed-laser",
            "program_id": "directed-energy",
            "source_signal_ids": ["demo-sig-lockheed-laser"],
            "supporting_evidence": [{"id": "demo-sig-lockheed-laser", "dataClassification": "public"}],
            "missing_information": [],
            "dedupe_key": "demo:closed:lockheed-watch",
            "owner": "Revenue Ops",
            "priority": "low",
            "status": "closed",
            "due_date": _at(reset_at, days=-2),
            "description": "Completed illustrative research item with an outcome for demo history.",
            "recommended_action": "Log Lockheed directed-energy watch item",
            "approval_state": "not_required",
            "execution_state": "not_started",
            "outcome": "Logged as a watch item for the next quarterly account planning review.",
            "outcome_category": "learning",
            "follow_up_date": due_next_week,
        },
    ]

    assistant_citations = [
        {
            "id": "signal:demo-sig-lockheed-laser:seed",
            "source_type": "signal",
            "record_id": "demo-sig-lockheed-laser",
            "title": "Pentagon picks Lockheed, nLIGHT for laser defense project",
            "route": "/accounts/demo-acct-lockheed",
            "claim": "Confirmed relationship-backed account development.",
            "claim_classification": "fact",
            "data_classification": "public",
            "relationship_status": "confirmed",
        },
        {
            "id": "score:score-lockheed-accountA:seed",
            "source_type": "score",
            "record_id": "score-lockheed-accountA",
            "title": "accountAttractiveness score",
            "route": "/accounts/demo-acct-lockheed",
            "claim": "Derived score explanation from persisted score snapshot.",
            "claim_classification": "derived",
            "data_classification": "derived",
            "relationship_status": None,
        },
        {
            "id": "work_item:demo-wi-approve-lockheed:seed",
            "source_type": "work_item",
            "record_id": "demo-wi-approve-lockheed",
            "title": "Approve Lockheed directed-energy follow-up task",
            "route": "/work/demo-wi-approve-lockheed",
            "claim": "Open work item from the normal backend work queue.",
            "claim_classification": "fact",
            "data_classification": "operational",
            "relationship_status": None,
        },
    ]
    assistant_created = _at(reset_at, days=-1, hours=2)
    assistant_archived = _at(reset_at, days=-2, hours=3)

    return {
        "tenant": {
            "id": DEMO_TENANT_ID,
            "display_name": DEMO_DISPLAY_NAME,
            "is_demonstration": True,
            "reference_date": reset_at,
            "metadata": {
                "repositoryRevision": DEMO_REPOSITORY_REVISION,
                "dataProvenance": "Repository demo seed; internal CRM, contact, opportunity, and operating records are illustrative.",
                "programs": [
                    {"id": "directed-energy", "name": "Directed-energy laser defense", "dataClassification": "public"},
                    {"id": "laser-power", "name": "Laser power transmission", "dataClassification": "public"},
                ],
                "contacts": [
                    {"id": "demo-contact-lockheed-1", "company_id": "demo-acct-lockheed", "name": "Alyssa Hart", "title": "Simulated Lockheed relationship owner", "dataClassification": "simulated"},
                    {"id": "demo-contact-nlight-1", "company_id": "demo-acct-nlight", "name": "Contact not provided", "title": "More information needed", "dataClassification": "simulated"},
                ],
                "opportunities": [
                    {"id": "demo-opp-lockheed-laser", "company_id": "demo-acct-lockheed", "name": "Directed-energy machining discovery", "value": 750000, "stage": "qualified", "close_date": due_next_week.date().isoformat(), "dataClassification": "simulated"},
                ],
                "facilities": [
                    {"id": "demo-facility-austin-cell", "company_id": "demo-acct-lockheed", "city": "Austin", "state": "TX", "address": "Illustrative BTX partner cell", "lat": 30.2672, "lon": -97.7431, "kind": "plant", "dataClassification": "simulated"}
                ],
                "sourceHealth": [
                    {"sourceKey": "hubspot-demo", "displayName": "Illustrative CRM seed", "availability": "simulated", "connectionMode": "snapshot_loaded", "environment": "developer", "dataMode": "simulated_internal", "canRead": True, "canWrite": False, "recordCount": 4, "lastSuccessfulSyncAt": _iso(reset_at), "errorCode": None, "errorMessage": "CRM records are illustrative for this demonstration workspace."},
                    {"sourceKey": "monitor", "displayName": "Monitor pipeline", "availability": "stale", "connectionMode": "snapshot_loaded", "environment": "none", "dataMode": "stored_snapshot", "canRead": True, "canWrite": False, "recordCount": 3, "lastSuccessfulSyncAt": _iso(detected_yesterday), "errorCode": None, "errorMessage": None},
                    {"sourceKey": "operating", "displayName": "ERP / MES operating data", "availability": "not_configured", "connectionMode": "not_configured", "environment": "none", "dataMode": "missing", "canRead": False, "canWrite": False, "recordCount": 0, "errorCode": "not_configured", "errorMessage": "Operating data is not connected; capacity findings are illustrative manual checks."},
                ],
                "notice": "Public intelligence is sourced. Internal BTX records are illustrative.",
            },
        },
        "accounts": accounts,
        "signals": signals,
        "relationships": relationships,
        "work_items": work_items,
        "notes": [
            {"id": "demo-note-approve-1", "work_item_id": "demo-wi-approve-lockheed", "author_user_id": "jamie.demo@btx.local", "body": "Simulated internal note: confirm whether the Lockheed laser team owns machining strategy before outreach.", "note_type": "finding", "evidence_ids": ["demo-sig-lockheed-laser"], "created_at": _at(reset_at, days=-1)},
            {"id": "demo-note-verified-1", "work_item_id": "demo-wi-verified-sim", "author_user_id": "system", "body": "Simulated verification: local demo record only. Reset did not create or verify a real HubSpot task.", "note_type": "verification", "evidence_ids": ["demo-sig-lockheed-laser"], "created_at": _at(reset_at, days=-1, hours=1)},
            {"id": "demo-note-closed-1", "work_item_id": "demo-wi-closed-outcome", "author_user_id": "revenue.ops@btx.local", "body": "Outcome recorded: keep the Lockheed directed-energy thread on watch and do not create a second outreach task yet.", "note_type": "outcome", "evidence_ids": ["demo-sig-lockheed-laser"], "created_at": _at(reset_at, days=-1)},
        ],
        "deliverables": [
            {
                "id": "demo-deliv-lockheed-brief",
                "type": "meeting_brief",
                "title": "Executive Account and Meeting Brief - Lockheed Martin Corporation",
                "canonical_account_id": "demo-acct-lockheed",
                "program_id": "directed-energy",
                "entity_ids": ["demo-acct-lockheed", "demo-sig-lockheed-laser"],
                "document": {
                    "id": "demo-deliv-lockheed-brief",
                    "type": "meeting_brief",
                    "title": "Executive Account and Meeting Brief - Lockheed Martin Corporation",
                    "createdAt": _iso(reset_at),
                    "brainArea": "accounts",
                    "entityIds": ["demo-acct-lockheed", "demo-sig-lockheed-laser"],
                    "dataClassification": "simulated",
                    "sections": [
                        {"id": "cover", "heading": "Cover", "blocks": [{"kind": "text", "text": "Account: Lockheed Martin Corporation. Meeting purpose: prepare an evidence-backed directed-energy account discussion. Meeting date: not supplied. Prepared for: BTX leadership and revenue team. Data freshness: monitor run is intentionally stale in this demo; internal CRM and work records are illustrative."}]},
                        {"id": "executive-summary", "heading": "Executive Summary", "blocks": [{"kind": "text", "text": "Public evidence supports a timely account review. Internal CRM context, opportunity value, and work states are simulated for the demonstration. Recommended posture: validate decision ownership and the production need before creating real outreach."}]},
                        {"id": "account-context", "heading": "Account Context", "blocks": [{"kind": "text", "text": "Lockheed is represented as a current customer account tied to directed-energy and aerospace production context. The named contact is simulated and should not be treated as a real person."}]},
                        {"id": "recent-developments", "heading": "Recent Developments", "blocks": [{"kind": "text", "text": "A sourced directed-energy development was linked to the account through a confirmed relationship record. The same source names nLIGHT, whose account link is still unconfirmed and is therefore held separately as a prospect to qualify."}]},
                        {"id": "decision-summary", "heading": "Decision Summary", "blocks": [{"kind": "text", "text": "Strategic attractiveness is supported by the score snapshot. Evidence strength is derived from the confirmed signal relationship. Likelihood to win, ability to deliver, and relationship strength remain decision aids, not guarantees."}]},
                        {"id": "meeting-preparation", "heading": "Meeting Preparation", "blocks": [{"kind": "text", "text": "Objectives: confirm the right stakeholder, validate the machining need, ask what timing and certifications matter, and agree on the next approved follow-up. Avoid unsupported live capacity claims."}]},
                        {"id": "current-work", "heading": "Current Work", "blocks": [{"kind": "text", "text": "Open work includes approval for a Lockheed directed-energy follow-up task and a verified simulated HubSpot task. The outcome remains visible as demonstration history."}]},
                        {"id": "sources-and-data-notes", "heading": "Sources And Data Notes", "blocks": [{"kind": "text", "text": "Sources: Breaking Defense public record, backend score snapshots, confirmed relationship review, and simulated BTX CRM/workflow records. Live internet research, ERP/MES capacity, email execution, and calendar execution are unavailable."}]},
                    ],
                    "sources": [{"source": "Breaking Defense", "records": ["demo-sig-lockheed-laser", "demo-rel-lockheed-laser", "score-lockheed-accountA", "demo-wi-approve-lockheed"], "reason": "Public directed-energy program development plus linked internal review, score, and work records."}],
                    "confidence": "high",
                    "actions": [],
                },
            }
        ],
        "assistant_conversations": [
            {
                "id": "demo-assist-lockheed",
                "title": "Ask: Lockheed directed-energy account",
                "status": "active",
                "created_by_user_id": "jamie.demo@btx.local",
                "context": {"account_id": "demo-acct-lockheed", "route": "/accounts/demo-acct-lockheed"},
                "related_account_id": "demo-acct-lockheed",
                "created_at": assistant_created,
                "updated_at": assistant_created,
                "archived_at": None,
            },
            {
                "id": "demo-assist-archive",
                "title": "Ask: archived source-health check",
                "status": "archived",
                "created_by_user_id": "revenue.ops@btx.local",
                "context": {"route": "/integrations"},
                "related_account_id": None,
                "created_at": assistant_archived,
                "updated_at": assistant_archived,
                "archived_at": assistant_archived,
            },
        ],
        "assistant_messages": [
            {
                "id": "demo-am-lockheed-user",
                "conversation_id": "demo-assist-lockheed",
                "role": "user",
                "content": "What should we do about Lockheed?",
                "status": "complete",
                "tool_activity": [],
                "citations": [],
                "related_records": [],
                "action_draft": None,
                "deliverable_draft": None,
                "metadata": {},
                "created_at": assistant_created,
            },
            {
                "id": "demo-am-lockheed-answer",
                "conversation_id": "demo-assist-lockheed",
                "role": "assistant",
                "content": "Based on internal records, the supported next step is to review the Lockheed directed-energy follow-up task. The account link is confirmed, the source is public, and the work item is waiting for approval. Live capacity and final owner/date details remain missing unless a cited internal record supplies them.",
                "status": "complete",
                "tool_activity": ["Reviewing account records", "Reading score explanation", "Checking open work", "Reviewing confirmed signals"],
                "citations": assistant_citations,
                "related_records": [
                    {"type": "account", "id": "demo-acct-lockheed", "title": "Lockheed Martin Corporation", "route": "/accounts/demo-acct-lockheed"},
                    {"type": "work_item", "id": "demo-wi-approve-lockheed", "title": "Approve Lockheed directed-energy follow-up task", "route": "/work/demo-wi-approve-lockheed"},
                ],
                "action_draft": None,
                "deliverable_draft": None,
                "metadata": {"orchestration": "internal_retrieval_v1"},
                "created_at": _at(reset_at, days=-1, hours=3),
            },
            {
                "id": "demo-am-archive-user",
                "conversation_id": "demo-assist-archive",
                "role": "user",
                "content": "Is operating data connected?",
                "status": "complete",
                "tool_activity": [],
                "citations": [],
                "related_records": [],
                "action_draft": None,
                "deliverable_draft": None,
                "metadata": {},
                "created_at": assistant_archived,
            },
            {
                "id": "demo-am-archive-answer",
                "conversation_id": "demo-assist-archive",
                "role": "assistant",
                "content": "Operating data is not connected in the demonstration workspace. Capacity findings are illustrative manual checks and should stay classified that way.",
                "status": "complete",
                "tool_activity": ["Reviewing account records"],
                "citations": [],
                "related_records": [],
                "action_draft": None,
                "deliverable_draft": None,
                "metadata": {"orchestration": "internal_retrieval_v1"},
                "created_at": _at(reset_at, days=-2, hours=4),
            },
        ],
    }
